name: C/C++ CI
on: push

jobs:
  build:
    name: Ubuntu + Cmake
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
